修复DataX部署问题-alert-rule缩进问题、对DataX进行持久化、调整Dockfile构建镜像-解决DataX需要用到Python和解决执行任务报错、修复bootstrap启动脚本-修复因datax可能启动太快导致无法连接MySQL执行重构表操作、移除之前捣鼓无效的DataX状态监控脚本

diff --git a/cloudeon-stack/EDP-2.0.0/datax/docker/Dockerfile b/cloudeon-stack/EDP-2.0.0/datax/docker/Dockerfile
--- a/cloudeon-stack/EDP-2.0.0/datax/docker/Dockerfile
+++ b/cloudeon-stack/EDP-2.0.0/datax/docker/Dockerfile
@@ -19,11 +19,15 @@ ADD datax-web-${DATAX_WEB_VERSION}.tar.gz \
     datax.tar.gz \
     freemarker-generator-cli-0.2.0-SNAPSHOT-app.tar.gz \
     jdk-11.0.24_linux-x64_bin.tar.gz \
-    mysql-community-client-8.4.4-el9.x86_64.tar.gz  /opt/
-
-RUN mv /opt/datax-web-* $DATAX_WEB_HOME
+    mysql-community-client-8.4.4-el9.x86_64.tar.gz /opt/
 
 RUN mv /opt/freemarker-generator-cli-* /opt/freemarker-generator-cli \
+    && mv /opt/datax-web-* $DATAX_WEB_HOME \
+    # 解决DataX执行需要用到Python环境
+    && dnf install -y python3 python3-pip \
+    && ln -s /usr/bin/python3 /usr/bin/python \
+    # 解决DataX执行任务报错：在有总bps限速条件下,单个channel的bps值不能为空,也不能为非正数
+    && sed -i 's/"byte": -1/"byte": 2000000/' "$DATAX_HOME/conf/core.json" \
     && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone \
     # 安装 MySQL 官方客户端命令（相比 MySQL Shell，磁盘空间占用小） \
     && dnf install -y /opt/mysql-community-client-plugins-8.4.4-1.el9.x86_64.rpm \
@@ -36,13 +40,12 @@ RUN mv /opt/freemarker-generator-cli-* /opt/freemarker-generator-cli \
     && dnf install -y procps \
     # 清理本地和下载的 rpm 安装包
     && rm -fv /opt/mysql-community-*.rpm \
-    && dnf clean all
-
-# 执行安装脚本并验证安装结果
-RUN chmod +x $DATAX_WEB_HOME/bin/install.sh && \
-    { echo "y"; } | $DATAX_WEB_HOME/bin/install.sh --force && \
+    && dnf clean all \
+    # 执行安装脚本并验证安装结果
+    && chmod +x $DATAX_WEB_HOME/bin/install.sh \
+    && { echo "y"; } | $DATAX_WEB_HOME/bin/install.sh --force \
     # 验证安装结果
-    test -d "$DATAX_WEB_HOME/modules" || { echo "Installation failed: modules directory not created"; exit 1; }
+    && test -d "$DATAX_WEB_HOME/modules" || { echo "Installation failed: modules directory not created"; exit 1; }
 
 # 暴露端口
 EXPOSE 8080 9999 9527
